# Generated by Django 5.2 on 2025-05-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
