# Generated by Django 5.2.4 on 2025-08-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
