# Generated by Django 5.2.4 on 2025-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_awb_code_order_city_order_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipment_id',
            new_name='shiprocket_shipment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='courier_company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
        ),
    ]
