# Generated by Django 5.2.4 on 2025-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_shipment_id_order_shiprocket_shipment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
